ProfanVBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static

from .views import hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

from blog import views


app_name='blog'


urlpatterns = [
    path('', views.index, name="index"),
    re_path(r'longgrids/(?P<slug>[a-z0-9-_]+)/$', views.longgrid_detail, name='longgrid_detail'),
    path('longgrids/', views.longgrids, name="longgrids"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

blog/models.py
from django.db import models

# Create your models here.


class Slider(models.Model):
    public = models.BooleanField(default=False, verbose_name='Опубликовать')
    sort = models.IntegerField(default=0, verbose_name='Номер для сортировки')
    title = models.CharField(max_length=255, null=True, verbose_name='Название слайда')
    image = models.ImageField(upload_to='media/', null=True, verbose_name='Изображение слайда')
    description = models.TextField(null=True, verbose_name='Описание')
    link_text = models.CharField(max_length=50, null=True, verbose_name='Текст ссылки')
    link = models.URLField(null=True, max_length=200)

    def __str__(self):
        return '{}'.format(self.title)


class LonggridTag(models.Model):
    name = models.CharField(null=True, unique=True, max_length=50, verbose_name='Тэг франшизы')
    slug = models.SlugField(max_length=50, null=True,
                            db_index=True, unique=True,
                            verbose_name='uri', help_text='Поле задает уникалный адрес объекта в разделе сайта')

    def __str__(self):
        return self.name


class Longgrid(models.Model):
    title = models.CharField(max_length=150, null=True, verbose_name='Название Лонггрида')
    slug = models.SlugField(max_length=100, blank=True, null=True, db_index=True, unique=True, verbose_name='uri')
    public = models.BooleanField(null=True, default=False, verbose_name='Опубликовать')
    date_pub = models.DateTimeField(auto_now_add=False, blank=True, verbose_name='Создан')
    image = models.ImageField(upload_to='media/', null=True, verbose_name='Изображение для превью')
    # short_description = WYSWYG
    detail_image = models.ImageField(upload_to='media/', null=True, verbose_name='Детальное изображение')
    # description =  WYSWYG
    tags = models.ManyToManyField(LonggridTag, blank=True, verbose_name="Теги статьи", related_name="Longgrid")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:longgrids", kwargs={"slug": self.slug})

ProfanVBlog/views.py
from django.http import HttpResponse

def hello(request):
    return HttpResponse('<h1> Hey Men. How are you? </h1>')

blog/views.py
import datetime

from django.shortcuts import render
from django.http import HttpResponse
from django.db import models
from django.utils import timezone
from blog.models import (Longgrid,
                         Slider
                         )



# Create your views here.

def index(request):
    now = timezone.now()    
    slide = Slider.objects.all()
    longgrids = Longgrid.objects.all()
    return render(request, 'blog/index.html', {'slide': slide, 'longgrids': longgrids}) 

def longgrids(request):
    longgrids = Longgrid.objects.all()
    return render(request, 'blog/longgrids.html', {'page': longgrids})

def longgrid_detail(request, slug):
    longgrid_detail = Longgrid.objects.all()
    return render(request, 'blog/longgrid_detail.html', {'page': longgrid_detail})

# def NBA(request):
#     NBA = NBA.objects.all()
#     return render(request, 'blog/NBA.html', {'NBA': longgrids})

blog/templates/blog/components/tag_list.html
{% if tags.all %}
    <div class="tags">
        <strong>Теги:&nbsp;</strong>
        {% for tag in tags.all %}
            <a href="">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
    </div>
{% endif %} 

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
    Profan Voice Main Page
{% endblock %}

    {% block content %}
        {% block name_page %}
            <h1> Main Page </h1>
        {% endblock %}
        <div>
          {% for l in longgrids %}
            <div class="card mb-3" style="max-width: 540px; margin: 20px auto;">
              <div class="row no-gutters">
                <div class="col-md-4">
                  <img src="{{ l.image.url }}" class="card-img" alt="...">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title">{{ l.title }}</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    <p class="card-text">
                        <small class="text-muted">
                            {% with l.tags as tags %}
                                {% include "blog/components/tag_list.html" %}
                            {% endwith %}
                        </small>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>  


    {% endblock %}

blog/templates/blog/longgrids.html
{% extends 'base.html' %}

{% block content %}

    <h3> Longgrid page </h3>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> {% endcomment %}
    <title>
      {% block title  %}
      {% endblock %}
    </title>

</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">NBA</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:longgrids' %}">Лонгриды</a>
            </li>
            {% comment %} <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Лонгриды
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Лонгрид-1</a>
                <a class="dropdown-item" href="#">Лонгрид-2</a>
                <a class="dropdown-item" href="#">Лонгрид-3</a>
              </div>
            </li> {% endcomment %}
            <li class="nav-item">
              <a class="nav-link" href="#">Циклы</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Подкасты</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>
    {% block content %}
      {% block name_page %}
      {% endblock %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>